### ISSUE TITLE
Add tests for managing focus when opening/closing sidebar

### ISSUE THREAD

**Issue by meganesu** [meganesu/generate-gb-opcodes#20]
In `app/index.spec.js`, there are tests that still needs to be implemented:

* `it.todo('moves focus to the sidebarRef');`
* `it.todo('moves focus back to the lastClickedInstructionRef');`

Tried so far:

* Using jest.spyOn.mockReturnValue to replace the ref returned from `useRef()` with something like `{ current: focus: jest.fn() }`. This worked for overwriting the initial value of sidebarRef, but once that ref gets set to the h3 element inside of DetailsSidebar, `current` gets overwritten again with the actual element.

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by meganesu** [comment]
@theashraf sounds good, I'll assign this issue to you. Thanks!
