### ISSUE TITLE
LD (HL), A is only 2 clock cycles?

### ISSUE THREAD

**Issue by fizaan** [meganesu/generate-gb-opcodes#30]
That can’t be right.

**Comment by meganesu** [comment]
And yet, here we are: https://archive.org/details/GameBoyProgManVer1.1/page/n95/mode/2up

Possibly the confusion is similar to what Michael Steil describes at 15:35 of [The Ultimate Game Boy Talk](https://youtu.be/HyzD8pNlpwI?t=935)? I'm putting everything in machine cycles, not clock cycles.

**Comment by fizaan** [comment]
Ah I see. My bad :)
